### ISSUE TITLE
It is not possible to pass a function as a parameter of another function. (CALLBACK)

### ISSUE THREAD

**Issue by matheusjohannaraujo** [HashLDash/Photon#109]
```python

def int add(int x, int y):
	return x + y

def test(cb callback):
	print(callback(1, 2))

test(add)

```

**Comment by HashLDash** [comment]
idea:
instead of typing the whole signature of the callback, use the inference in the call
For example:
```python
def test(int func callback):
    print(callback(1,2))
```
So callback will have the void* type and when we call the callback it will have (int int) for the argument signature, the return type would be missing, but we put int func so all types can be resolved now to create the signature

**Comment by HashLDash** [comment]
Void callbacks are possible by commit 2074f86
