### ISSUE TITLE
Photon types

### ISSUE THREAD

**Issue by juanjavatus** [HashLDash/Photon#139]
Hi, here I go again. My question is about types. There exists long or double types? When I've tried to get a timestamp from time lib I've got type error in argument.

This is the .w code:

import time

int t = time(NULL)
str date = ctime(t)
print(date)

This is the error I get:

Sources/c/main.c: In function ‘main’:
Sources/c/main.c:13:24: warning: passing argument 1 of ‘ctime’ makes pointer from integer without a cast [-Wint-conversion]
   13 |     char* date = ctime(t);
      |                        ^
      |                        |
      |                        long int
In file included from Sources/c/main.c:5:
/usr/include/time.h:142:14: note: expected ‘const time_t *’ {aka ‘const long int *’} but argument is of type ‘long int’
  142 | extern char *ctime (const time_t *__timer) __THROW;
      |              ^~~~~
Regards

**Comment by Huyston** [comment]
Hey :)
Actually, int in photon is equivalent to a long in C. And float in photon is equivalent to double in C. So, yes there are long and double types.

You can also cast to a native type (not all yet), but for example:
double t = 0   (photon will see that 0 is int, but you are forcing the double type, so it will cast to double)
Notice that casting to native types will only work on that specific target. C in this example.

In your specific example, the code is wrong. 
- There is no "time" library in photon, so you are actually importing the "time.h" C library
- the time function doesn't return a value. It changes the value of the variable address you pass to it
- ctime actually needs a const time_t *

I'm still wondering if I should provide the addr() and ptr() API to interact with native C directly from Photon. Because there are so many different things in all languages, providing this will make the language very complex. Instead you could write a date function in C and use it in Photon.

In the future we will have a time library. If you want to make it, it would be awesome! Check the lib folder for insights on that.

**Comment by juanjavatus** [comment]
import for photon imports, cimport for native c, pyimport for python... should be useful

**Comment by HashLDash** [comment]
Yes, I like that. My only concern is that it may not work on all targets. Making this a language statement can cause confusion that it always work, while it may not.
